
services:
  web1:
    build:
      context: .
    container_name: web1
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: node server.js

  web2:
    build:
      context: .
    container_name: web2
    ports:
      - "3002:3000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: node server.js

  web3:
    build:
      context: .
    container_name: web3
    ports:
      - "3003:3000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: node server.js

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web1
      - web2
      - web3

  admin:
    build:
      context: ./adminggg
    ports:
      - "8080:8080"
    volumes:
      - ./adminggg:/usr/src/app
    working_dir: /usr/src/app
    command: node serveradmin.js

  graphql:
    build:
      context: ./graphql_development
    ports:
      - "4000:4000"
    volumes:
      - ./graphql_development:/usr/src/app
    working_dir: /usr/src/app
    command: node server.js

  websocket:
    build:
      context: .
    ports:
      - "4040:4040"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: node websocket.js